testException: #{"name":"testException","time":1445945952369,"date":"2015-10-27 07:39:12,369","level":"INFO","thread":"quoted\"","message":"new line\n and {}","exceptionclass":"java.net.NoRouteToHostException","stack":["java.net.NoRouteToHostException: that box caught fire 3 years ago","\tat org.apache.hadoop.log.TestLog4Json.testException(TestLog4Json.java:63)","\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)","\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.lang.reflect.Method.invoke(Method.java:606)","\tat junit.framework.TestCase.runTest(TestCase.java:176)","\tat junit.framework.TestCase.runBare(TestCase.java:141)","\tat junit.framework.TestResult$1.protect(TestResult.java:122)","\tat junit.framework.TestResult.runProtected(TestResult.java:142)","\tat junit.framework.TestResult.run(TestResult.java:125)","\tat junit.framework.TestCase.run(TestCase.java:129)","\tat junit.framework.TestSuite.runTest(TestSuite.java:255)","\tat junit.framework.TestSuite.run(TestSuite.java:250)","\tat org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)","\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)","\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)","\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)"]}#
testLog: #{"name":"test","time":1445945952436,"date":"2015-10-27 07:39:12,436","level":"INFO","thread":"main","message":"test message"}#
testConstruction: #{"name":"name","time":0,"date":"1969-12-31 19:00:00,000","level":"DEBUG","thread":"thread1","message":"hello, world"}#
testNestedException: #{"name":"testNestedException","time":1445945952440,"date":"2015-10-27 07:39:12,440","level":"INFO","thread":"quoted\"","message":"new line\n and {}","exceptionclass":"java.io.IOException","stack":["java.io.IOException: Datacenter problems","\tat org.apache.hadoop.log.TestLog4Json.testNestedException(TestLog4Json.java:83)","\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)","\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.lang.reflect.Method.invoke(Method.java:606)","\tat junit.framework.TestCase.runTest(TestCase.java:176)","\tat junit.framework.TestCase.runBare(TestCase.java:141)","\tat junit.framework.TestResult$1.protect(TestResult.java:122)","\tat junit.framework.TestResult.runProtected(TestResult.java:142)","\tat junit.framework.TestResult.run(TestResult.java:125)","\tat junit.framework.TestCase.run(TestCase.java:129)","\tat junit.framework.TestSuite.runTest(TestSuite.java:255)","\tat junit.framework.TestSuite.run(TestSuite.java:250)","\tat org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)","\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)","\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)","\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)","Caused by: java.net.NoRouteToHostException: that box caught fire 3 years ago","\tat org.apache.hadoop.log.TestLog4Json.testNestedException(TestLog4Json.java:81)","\t... 19 more"]}#
testLogExceptions: #{"name":"test","time":1445945952498,"date":"2015-10-27 07:39:12,498","level":"INFO","thread":"main","message":"test message","exceptionclass":"java.io.IOException","stack":["java.io.IOException: startup failure","\tat org.apache.hadoop.log.TestLog4Json.testLogExceptions(TestLog4Json.java:136)","\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)","\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.lang.reflect.Method.invoke(Method.java:606)","\tat junit.framework.TestCase.runTest(TestCase.java:176)","\tat junit.framework.TestCase.runBare(TestCase.java:141)","\tat junit.framework.TestResult$1.protect(TestResult.java:122)","\tat junit.framework.TestResult.runProtected(TestResult.java:142)","\tat junit.framework.TestResult.run(TestResult.java:125)","\tat junit.framework.TestCase.run(TestCase.java:129)","\tat junit.framework.TestSuite.runTest(TestSuite.java:255)","\tat junit.framework.TestSuite.run(TestSuite.java:250)","\tat org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)","\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)","\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)","\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)","\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)","Caused by: java.io.IOException: Directory / not found","\tat org.apache.hadoop.log.TestLog4Json.testLogExceptions(TestLog4Json.java:135)","\t... 19 more"]}#
